In [1]:
import os
import tensorflow as tf  # 导入 TF 库
from tensorflow import keras  # 导入 TF 子库
from tensorflow.keras import layers, optimizers, datasets  # 导入 TF 子库

print("\n","-------------type-------------", "\n")
floatData = 1.2
TensorData = tf.constant([1.2, 3.])  # 依list创建标量
print(type(floatData), type(TensorData), tf.is_tensor(TensorData), '\n')
afterData = tf.cast(TensorData, tf.float64)  # 转换精度
print(TensorData.dtype, afterData.dtype, '\n')
numpyData = TensorData.numpy()
print(type(numpyData), '\n')


 -------------type------------- 

<class 'float'> <class 'tensorflow.python.framework.ops.EagerTensor'> True 

Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

<dtype: 'float32'> <dtype: 'float64'> 

<class 'numpy.ndarray'> 



2022-12-25 11:41:28.108411: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-12-25 11:41:28.108495: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [8]:

print("\n","-------------創建張量-------------", "\n")
one = tf.ones([2,1])
print(one)

zero = tf.zeros([1,2])
print(zero)

fill = tf.fill([2,2],-3) # 自定义数值张量
print(fill)

like = tf.ones_like(fill) # 相同張量的1
print(like)



 -------------創建張量------------- 

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[-3 -3]
 [-3 -3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [17]:

print("\n","-------------創建已知分佈向量-------------", "\n")
normal = tf.random.normal([2,2]) # 创建均值为 0，标准差为 1 的常態分布
normal2 = tf.random.normal([2,2], mean=1,stddev=2)  # 创建均值为 1，标准差为 2 的常態分布
print(normal, normal2)

uniform = tf.random.uniform([2,2])
uniform2 = tf.random.uniform([2,2] , maxval=10) # 從[0,10]區間的平均分佈
print(uniform,uniform2)


range1 = tf.range(10,20, delta=2) # [10,20]步長為2的序列
print(range1)


 -------------創建已知分佈向量------------- 

tf.Tensor(
[[ 8.3630286e-02 -2.0070019e-04]
 [ 4.5356688e-01 -4.8913056e-01]], shape=(2, 2), dtype=float32) tf.Tensor(
[[ 1.2865667   5.546808  ]
 [ 0.3312955  -0.37487435]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.6502187  0.3562609 ]
 [0.93059504 0.01472116]], shape=(2, 2), dtype=float32) tf.Tensor(
[[6.5021873  3.562609  ]
 [9.30595    0.14721155]], shape=(2, 2), dtype=float32)
tf.Tensor([10 12 14 16 18], shape=(5,), dtype=int32)


In [19]:
print("\n","-------------MSE實戰-------------", "\n")
out = tf.random.uniform([4,10]) #随机模拟网络输出
y = tf.constant([2,3,2,0]) # 随机构造样本真实标签
y = tf.one_hot(y, depth=10) # one-hot编码
loss = tf.keras.losses.mse(y, out) # 计算每个样本的MSE
loss = tf.reduce_mean(loss) # 平均MSE 
print(loss)



 -------------MSE實戰------------- 

tf.Tensor(0.36244085, shape=(), dtype=float32)


In [3]:

print("\n","-------------圖片處理實戰-------------", "\n")
(x, y), (x_val, y_val) = datasets.mnist.load_data()  # 加载数据集
x = 2 * tf.convert_to_tensor(x, dtype=tf.float32) / 255. - 1  # 转换为张量，缩放到-1~1
y = tf.convert_to_tensor(y, dtype=tf.int32)  # 转换为张量
y = tf.one_hot(y, depth=10)  # one-hot编码
print(x.shape, y.shape, '\n')
train_dataset = tf.data.Dataset.from_tensor_slices((x, y))  # 构建数据集对象
print('<TensorSliceDataset>:', '\n', train_dataset, '\n')
train_dataset = train_dataset.batch(512)  # 批量训练
print('<BatchDataset>:', '\n', train_dataset, '\n')



 -------------實際演練------------- 

(60000, 28, 28) (60000, 10) 

<TensorSliceDataset>: 
 <TensorSliceDataset element_spec=(TensorSpec(shape=(28, 28), dtype=tf.float32, name=None), TensorSpec(shape=(10,), dtype=tf.float32, name=None))> 

<BatchDataset>: 
 <BatchDataset element_spec=(TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name=None), TensorSpec(shape=(None, 10), dtype=tf.float32, name=None))> 

