对于2个样本的输入X，我们需要将偏置𝒃的改为(2,3)。

- 維度變換包含了改變視圖 `reshape`，
- 插入新維度 `expand_dims`，
- 刪除維度 `squeeze`，
- 交換維度 `transpose`，
- 複製數據 `tile `等

> 改變視圖、增刪維度都不會影響張量的存儲。

Broadcasting機制會針對於最常見的場景自動完成增加維度並複制數據的功能。
- tf.broadcast_to(x, new_shape)

In [27]:
import tensorflow as tf  # 导入 TF 库
print("------------reshape--------------", "\n")
x=tf.range(96)
x=tf.reshape(x,[2,4,4,3]) # (2, 4, 4, 3) 2*4*4*3=96
print(x.shape)
x=tf.reshape(x,[2,4,-1]) # (2, 4, 12)
print(x.shape)
x=tf.reshape(x,[2,-1,3]) # (2, 16, 3)
print(x.shape)


------------reshape-------------- 

(2, 4, 4, 3)
(2, 4, 12)
(2, 16, 3)


In [28]:
print("------------expand_dims--------------", "\n")
x = tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
print(x.shape)
x1 = tf.expand_dims(x,axis=0) # (1, 28, 28)
print(x1.shape)
x2 = tf.expand_dims(x,axis=2) # (28, 28, 1)
print(x2.shape)

------------expand_dims-------------- 

(28, 28)
(1, 28, 28)
(28, 28, 1)


In [29]:
print("------------squeeze--------------", "\n")
x1 = tf.squeeze(x1,axis=0) # (28, 28)
print(x1.shape)
x2 = tf.squeeze(x2,axis=2) # (28, 28)
print(x2.shape)

------------queeze-------------- 

(28, 28)
(28, 28)


In [30]:
print("------------transpose--------------", "\n")
x = tf.random.normal([2,32,48,3])
x = tf.transpose(x,perm=[0,2,1,3])
x

<tf.Tensor: shape=(2, 48, 32, 3), dtype=float32, numpy=
array([[[[ 1.0698228 , -0.41428247,  1.0446824 ],
         [ 0.6560779 ,  0.08529086, -0.13709766],
         [ 0.94200903,  0.3627595 ,  0.12820646],
         ...,
         [-1.1260175 ,  0.4496668 ,  0.4475333 ],
         [-0.43626088, -1.015933  , -0.23015691],
         [ 0.7724027 , -1.0063405 , -1.4186926 ]],

        [[ 1.2803454 , -0.2508778 , -1.2549438 ],
         [ 0.01352589, -0.3502329 , -0.5361643 ],
         [ 1.3919983 , -0.2987943 ,  0.9090634 ],
         ...,
         [-0.18580101,  0.9662927 , -0.320431  ],
         [-0.5391332 ,  0.67536974, -0.49983147],
         [-0.12106893,  1.200654  , -0.56365806]],

        [[-0.6445651 , -0.71179354, -1.0566994 ],
         [-2.1936026 ,  1.3663781 , -2.482687  ],
         [ 0.73453593,  1.8521591 ,  0.42786986],
         ...,
         [ 0.43617487, -0.7029779 ,  0.7296327 ],
         [-0.52546364,  1.0153353 , -0.1787239 ],
         [-1.2302692 ,  0.25965282,  0.42558408]

In [32]:
print("------------title--------------", "\n")
b = tf.constant([1,2])
print(b.shape)
b = tf.expand_dims(b, axis=0)
b = tf.tile(b, multiples=[2,1])
print(b.shape)

------------title-------------- 

(2,)
(2, 2)


In [38]:
print("------------broadcast_to--------------", "\n")
A = tf.constant([0,1,2])
tf.broadcast_to(A, [2,6,6,3])

------------broadcast_to-------------- 



<tf.Tensor: shape=(2, 6, 6, 3), dtype=int32, numpy=
array([[[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]],


       [[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0,